export const technologies = [
  {
    category: "Frontend Frameworks",
    items: ["react", "Angular", "nextjs"],
  },
  {
    category: "CSS Frameworks",
    items: [
      "Tailwind CSS",
      "Bootstrap",
      "Sass",
      "Shadcn",
      "MUI",
      "AntDesign",
      "Styled Components",
    ],
  },
  {
    category: "Libraries",
    items: [
      "React Router",
      "React Query",
      "TanStack Table",
      "Axios",
      "gsap",
      "framer-motion",
      "Formik",
      "Yup",
      "Zod",
      "Joi",
      "react-hook-form",
    ],
  },
  {
    category: "State Management",
    items: ["Redux", "Redux Toolkit", "Context API", "zustand"],
  },
  {
    category: "Programming Languages",
    items: ["javascript", "typescript", "Python", "Java", "C++"],
  },
  {
    category: "Tools",
    items: [
      "Git",
      "Docker",
      "Jenkins",
      "AWS",
      "Husky",
      "Vercel",
      "Monorepo",
      "firebase",
      "Pusher",
    ],
  },
];

export const experiences = [
  {
    title: "Mid Level Frontend Developer",
    company: "MTL (Part Time)",
    period: "2024-12 - Present",
    description:
      "Working as a Frontend Developer using Next.js, responsible for developing and maintaining the company's internal system",
  },
  {
    title: "Mid Level Frontend Developer",
    company: "IJD Creatives",
    period: "2024-11 - Present",
    description:
      "Led the frontend development team in creating responsive and accessible web applications using React and Next.js.",
    skills: ["gsap", "react", "Next.js", "Management"],
  },
  {
    title: "AI Engineer",
    company: "Rology",
    period: "2024-07 - 2024-10",
    description:
      "Project based (remote) — building an auto impression system using LLM",
    skills: ["Python", "LLAMA3", "HuggingFace", "LLM"],
  },
  {
    title: "Frontend Developer",
    company: "FiveM Technologies",
    period: "2024-03 - 2024-11",
    description:
      "Developed and maintained ERP system, focusing on performance optimization and cross-browser compatibility.",
    skills: [
      "typescript",
      "nextjs",
      "tailwindcss",
      "AntDesign",
      "react-hook-form",
      "Webpack",
    ],
  },
  {
    title: "Machine Learning Engineer (internship)",
    company: "Radical AI",
    period: "2023-10 - 2023-12",
    description: "Built a chatbot using LLM for interview simulation",
    skills: ["Python", "API", "HuggingFace", "LLM", "LangChain"],
  },
  {
    title: "Junior Web Developer",
    company: "Dr Code",
    period: "2023-10 - 2024-03",
    description:
      "Assisted in building responsive websites and dashboards, and implemented UI/UX designs using modern frontend technologies.",
    skills: ["HTML5", "CSS3", "react", "javascript", "Bootstrap", "Formik", "MUI"],
  },
  {
    title: "Data Scientist",
    company: "Dr Code",
    period: "2022-06 - 2022-07",
    description:
      "Project based (remote) — built an AI system for automatic extraction of data from invoices",
    skills: ["Python", "Pandas", "NumPy", "TensorFlow", "YOLO", "Image preprocessing"],
  },
];

export type Skills = 'python'
|"mui"|"yup"
|'package'| 'javascript'|'firebase' | 'react-hook-form'|'bootstrap'|'shadcn' | 'typescript' | 'react' | 'nextjs' | 'tailwindcss' | 'Joi' | 'docker' | 'aws' | 'git' | 'html' | 'css' | 'nodejs' | 'AntDesign' | 'mongodb' | 'sql' | 'java' | 'c++' | 'zustand' | 'data science' | 'llm' | 'huggingface' | 'gsap' | 'framer-motion';
export type Project = {
  id: string;
  title: string;
  summary: string;
  technologies: Skills[];
  primaryTech: string;
  image: string;
  liveUrl: string;
  githubUrl: string;
  year: string;
  roles: string[];
  customer: string;
};
export const projects: Project[] = [
  {
    id: "smooth-erp-1",
    title: "Smooth-ERP",
    summary: "ERP dashboard and admin panel for Smooth-ERP.",
    technologies: ["nextjs", "react", "react-hook-form", "Joi", "tailwindcss", "typescript", "AntDesign"],
    primaryTech: "nextjs",
    image: "/images/smooth-erp.png",
    liveUrl: "https://test.smootherp.com/ar",
    githubUrl: "",
    year: "2024",
    roles: ["Frontend", "UI/UX"],
    customer: "Smooth-ERP",
  },
  {
    id: "she-bake-23",
    title: "She Bake",
    summary: "E‑commerce landing and store demo built with Next.js and Tailwind.",
    technologies: ["nextjs", "react", "tailwindcss", "typescript", "zustand"],
    primaryTech: "nextjs",
    image: "/images/sheBake.png",
    liveUrl: "https://she-bake.vercel.app/",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "lensjs-12",
    title: "LensJS",
    summary: "A small open-source package demo.",
    technologies: ["react", "package"],
    primaryTech: "react",
    image: "/images/lens.png",
    liveUrl: "https://lensjs.vercel.app/",
    githubUrl: "https://github.com/lensjs/lens",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "Waffer-13",
    title: "Waffer",
    summary: "A medical E-commerce Platform",
    technologies: ["nextjs", "typescript", "react",'react-hook-form','tailwindcss','shadcn'],
    primaryTech: "nextjs",
    image: "/images/waffer.png",
    liveUrl: "https://wafferapp.app/ar",
    githubUrl: "",
    year: "2025",
    roles: [],
    customer: "",
  },  {
    id: "ijdcreatives-13",
    title: "ijdcreatives",
    summary: "A Creative Agency Platform",
    technologies: ["nextjs", "typescript", "react",'react-hook-form','tailwindcss','shadcn'],
    primaryTech: "nextjs",
    image: "/images/ijdcreatives.png",
    liveUrl: "https://ijdcreatives.com/",
    githubUrl: "",
    year: "2025",
    roles: [],
    customer: "",
  },  {
    id: "Arep-13",
    title: "Arep",
    summary: "A medical E-commerce Platform",
    technologies: ["nextjs", "typescript", "react",'react-hook-form','tailwindcss','shadcn'],
    primaryTech: "nextjs",
    image: "/images/arep.png",
    liveUrl: "https://arep.wovenclouds.com/ar",
    githubUrl: "",
    year: "2025",
    roles: [],
    customer: "",
  }, {
    id: "UrPath-13",
    title: "UrPath",
    summary: "A Course Booking and Organization Platform",
    technologies: ["nextjs", "typescript", "react",'react-hook-form','tailwindcss','shadcn'],
    primaryTech: "nextjs",
    image: "/images/urpath.png",
    liveUrl: "https://urpath.sa/ar",
    githubUrl: "",
    year: "2025",
    roles: [],
    customer: "",
  }, {
    id: "deliverus-13",
    title: "deliverus",
    summary: "A Logistics and Delivery Platform",
    technologies: ["nextjs", "typescript", "react",'tailwindcss','shadcn'],
    primaryTech: "nextjs",
    image: "/images/deliverus.png",
    liveUrl: "https://deliverus.sa/ar",
    githubUrl: "",
    year: "2025",
    roles: [],
    customer: "",
  },
    {
    id: "aroovia-13",
    title: "Aroovia",
    summary: "Marketing site built with Angular.",
    technologies: ["nextjs", "typescript", "react",'react-hook-form','tailwindcss','shadcn'],
    primaryTech: "Angular",
    image: "/images/aroovia.png",
    liveUrl: "https://aroovia.com/",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "smooth-erp-site-2",
    title: "Smooth-ERP (marketing site)",
    summary: "Public marketing site for Smooth-ERP.",
    technologies: ["nextjs", "tailwindcss", "typescript", "react", "framer-motion", "gsap"],
    primaryTech: "nextjs",
    image: "/images/smooth-erp-site.png",
    liveUrl: "https://smootherp.com/",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "naqrah-3",
    title: "Naqrah",
    summary: "Landing page / coming soon site.",
    technologies: ["nextjs", "tailwindcss", "typescript", "react", "framer-motion"],
    primaryTech: "nextjs",
    image: "/images/naqrah.png",
    liveUrl: "https://naqrah-comming-soon.vercel.app/en",
    githubUrl: "https://github.com/mahmoudbahaa755/naqrah-comming-soon",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "fivemtech-4",
    title: "FiveM Tech",
    summary: "Company site built with modern frontend stack.",
    technologies: ["nextjs", "tailwindcss", "typescript", "react", "framer-motion"],
    primaryTech: "nextjs",
    image: "/images/5m-tech.png",
    liveUrl: "https://5m-tech.com/",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "FiveM Tech",
  },
  {
    id: "rayed-11",
    title: "Rayed Site",
    summary: "Multi-language site built with Next.js.",
    technologies: ["nextjs", "tailwindcss", "typescript"],
    primaryTech: "nextjs",
    image: "/images/rayed.png",
    liveUrl: "https://rayed.net/en",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "hyperfinition-5",
    title: "Hyperfinition",
    summary: "Corporate marketing site using MUI.",
    technologies: ["tailwindcss", "typescript", "react", "mui", "yup"],
    primaryTech: "react",
    image: "/images/hyper.png",
    liveUrl: "https://site.hyperfinition.com/",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "pahu-6",
    title: "Pahu",
    summary: "Landing page with gsap interactions.",
    technologies: ["nextjs", "tailwindcss", "typescript", "react", "gsap"],
    primaryTech: "gsap",
    image: "/images/pahu.png",
    liveUrl: "https://pahu-landing-ijd.vercel.app/",
    githubUrl: "",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "todo-7",
    title: "To Do List",
    summary: "Small demo app using firebase.",
    technologies: ["javascript", "react", "firebase"],
    primaryTech: "react",
    image: "/images/toDoList.png",
    liveUrl: "https://to-do-list-react-nu-coral.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/to-do-list--React-",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "restaurant-8",
    title: "Restaurant Menu",
    summary: "Interactive menu demo built with React.",
    technologies: ["javascript", "react", "firebase"],
    primaryTech: "react",
    image: "/images/Restaurant.png",
    liveUrl: "https://restaurant-react-lip8hvqbn-mahmoud-bahaas-projects.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/Restaurant-react",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "formpage-9",
    title: "Form Page",
    summary: "Form demonstrations using MUI components.",
    technologies: ["javascript", "react", "mui"],
    primaryTech: "react",
    image: "/images/formPage.png",
    liveUrl: "https://form-three-snowy.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/Form",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "portfolio-10",
    title: "First Portfolio",
    summary: "My original portfolio project.",
    technologies: ["javascript", "nextjs", "react", "css"],
    primaryTech: "nextjs",
    image: "/images/p.png",
    liveUrl: "https://github.com/mahmoudbahaa755/portifolio",
    githubUrl: "https://portifolio-ten-tawny.vercel.app/",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "padel-club-23",
    title: "Padel Club",
    summary: "Landing page for a sports club.",
    technologies: ["nextjs", "react", "tailwindcss", "typescript"],
    primaryTech: "nextjs",
    image: "/images/paddel.png",
    liveUrl: "https://padel-club-landing-page.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/padel-club-landing-page",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "shoppinglist-4",
    title: "Shopping List",
    summary: "Simple React shopping list demo.",
    technologies: ["javascript", "react"],
    primaryTech: "react",
    image: "/images/shopinglist.png",
    liveUrl: "https://react-shopping-list-9kn0j19qk-mahmoud-bahaas-projects.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/react-shopping-list",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "loan-template-1",
    title: "Loan Template",
    summary: "Static HTML/CSS template hosted on GitHub Pages.",
    technologies: ["javascript", "html", "css"],
    primaryTech: "HTML/CSS",
    image: "/images/loanTemplate.png",
    liveUrl: "https:/mahmoudbahaa12.github.io/Loan-Template/",
    githubUrl: "https://github.com/mahmoudbahaa12/Loan-Template",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "minx-5",
    title: "Minx Template",
    summary: "Template built with Bootstrap.",
    technologies: ["javascript", "html", "css", "bootstrap"],
    primaryTech: "Bootstrap",
    image: "/images/minx.png",
    liveUrl: "https://template-3-eight.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/Minx-Template",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "todo-6-duplicate",
    title: "To Do List (duplicate)",
    summary: "Duplicate entry — consider removing one.",
    technologies: ["javascript", "react", "firebase"],
    primaryTech: "react",
    image: "/images/toDoList.png",
    liveUrl: "https://to-do-list-react-nu-coral.vercel.app/",
    githubUrl: "https://github.com/mahmoudbahaa755/to-do-list--React-",
    year: "",
    roles: [],
    customer: "",
  },
  {
    id: "web-scrapping-7",
    title: "Web Scrapping",
    summary: "A small python scraping project.",
    technologies: ["python", "html"],
    primaryTech: "Python",
    image: "/images/wuzzef.png",
    liveUrl: "https://github.com/mahmoudbahaa755/web-scrapping-wuzzef-",
    githubUrl: "https://github.com/mahmoudbahaa755/web-scrapping-wuzzef-",
    year: "",
    roles: [],
    customer: "",
  },
];